### ISSUE TITLE
Water Supply

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/Vacation_Rental#16]
@rvzenteno The existing main water supply pipe is 1".

I see you're looking for a 2"

If we can't change this to a 2", would we need a pressure tank?

Thanks, Ryan

![image](https://cloud.githubusercontent.com/assets/507113/25590502/684ee1c0-2e76-11e7-9bc6-78161a476bb6.png)

**Comment by apbock** [comment]
The answer to this would depend on Roberto's water calculations and the existing water pressure.

**Comment by theoryshaw** [comment]
Sounds good. I will ask GC (Brent) to get a plumber to test existing water pressure. 

For permit, let just assume there's a 2" line (or whatever is needed) there.

**Comment by rvzenteno** [comment]
I'll take a look at this after work.

**Comment by rvzenteno** [comment]
Sorry, I pressed the wrong button.

**Comment by rvzenteno** [comment]
I updated the loads and it turns out to be a 1-1/2". I was able to import the Water calculation Worksheet Aaron sent me. Now, This is something new to me. If Aaron can help me filling it out I would appreciate it very much. I'll post the Excel file to the Project Github.

**Comment by apbock** [comment]
Roberto, you can post the file or email it to me. The only needed piece of information we don't have is the incoming water pressure; the rest can be determined by what you have modeled. I can fill in what's known and explain how I did it.
If we don't immediately have the water pressure, we could consider omitting the calcs on the sheet altogether but the reviewer will likely flag this. Either that or we make an assumption on pressure and verify it later in the field. Either way, if there were working fixtures on the top floor prior to the remodel, the new ones will almost certainly work as well.
Thanks.
Aaron


Sent from my U.S. Cellular® Smartphone

-------- Original message --------

**Comment by theoryshaw** [comment]
Good call, at this point, let's just assume an existing water pressure that works. 

We'll verify later. 

Thanks.

**Comment by rvzenteno** [comment]
Aaron, The files are posted. If you do fill the Excel file send it to me and I"ll convert it to import it to the Revit Model.

Thanks,

**Comment by apbock** [comment]
Can you tell me where this is located or otherwise email me the file? I can't find it.

**Comment by rvzenteno** [comment]
It is in the same folder as the PDF I created and posted on the PERMIT
FOLDER.


On May 3, 2017 at 1:51 PM, <apbock <notifications@github.com>> wrote:

Can you tell me where this is located or otherwise email me the file? I
can't find it.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/OpeningDesign/Vacation_Rental/issues/16#issuecomment-298985871>,
or mute the thread

**Comment by theoryshaw** [comment]
Hi Aaron... 
https://github.com/OpeningDesign/Vacation_Rental/tree/master/Transfer/20170503%20-----%20ISSUE%20FOR%20PERMIT%20------

**Comment by apbock** [comment]
I've filled out the calculation worksheet and posted it back to that folder. I calculated a demand of 33 gpm maximum based on WI code fixture units and used that in the worksheet. I assumed 35 psi at the building entrance and used pipe lengths and building elevations to get the rest.

**Comment by theoryshaw** [comment]
Hi Guys, The existing water pressure is 85psi, and the existing pipe is 1". 

Please let me know if that affects anything, one way or the other. 

Thanks, Ryan

**Comment by theoryshaw** [comment]
Hi @rvzenteno Can you let me know if this new info affects anything?

thanks.

**Comment by rvzenteno** [comment]
Hey Ryan, sorry for not replying sooner. Typically we would want no more
that 45 PSI. I would typically add a PRV to reduce the pressure into the
building. But because we need to have the 1 1/2" pipe the tank that you
mentioned will probably be needed. As an alternative  an expantion tank
could serve the same purpose to handle the pressure and add to the load
requirement. I think this would be the same as the holding tank you
mentioned before.

Thanks.


On May 18, 2017 at 1:08 PM, <Ryan Schultz <notifications@github.com>>
wrote:

Hi @rvzenteno <https://github.com/rvzenteno> Can you let me know if this
new info affects anything?

thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpeningDesign/Vacation_Rental/issues/16#issuecomment-302475709>,
or mute the thread

**Comment by theoryshaw** [comment]
Thanks Roberto.  @apbock would you concur?

**Comment by apbock** [comment]
I have no issue with 45 psi.
Just so I'm clear, what is the expansion/holding tank for? I typically only see these on water heaters and pumped systems.
Thanks.
Aaron


Sent from my U.S. Cellular® Smartphone

-------- Original message --------
